# Generated by Django 5.0.2 on 2024-02-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_at',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 2, 24, 10, 48, 41, 576544, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
